### ISSUE TITLE
[BUG] Handle Null Intents in onStartCommand

### ISSUE THREAD

**Issue by alkebuware** [JulianAssmann/flutter_background#30]
**Describe the bug**
I'm getting some Crash reports in Crashlytics where the onStartCommand in IsolateHolderService.kt is called with a null Intent. It seems that variable is currently non-nullable type.

Caused by java.lang.IllegalArgumentException: Parameter specified as non-null is null: method f.n.c.i.d, parameter intent
       at de.julianassmann.flutter_background.IsolateHolderService.onStartCommand(IsolateHolderService.java:2)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4042)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**To Reproduce**
I've actually been unable to reproduce it in my local dev environment.

**Expected behavior**
The onStartCommand should instead take a nullable Intent type as a parameter and the intent.action call should be made null safe

**Smartphone:**
 - Device: Honor 7X, OS: 8.0.0
 - Device: LG G6, OS: 9
 - Device: A52, OS: 11
 - Device: Galaxy Note 8, OS: 9
 - Device: Moto X(4), OS: 9
 - Device: motorola one 5G UW, OS: 11
 - Device: moto z4, OS: 10
 - Device: Pixel 2 XL, OS: 11
 - Device: Galaxy S8, OS: 9
 - Device: Galaxy S21 5G, OS: 11
 - Device: Galaxy S7, OS: 8.0.0
 - Device: Galaxy S9, OS: 10
 - ....

**Comment by JulianAssmann** [comment]
Should be fixed by #31 
Thank you @alkebuware
