### ISSUE TITLE
android.app.RemoteServiceException

### ISSUE THREAD

**Issue by moubelkacem** [JulianAssmann/flutter_background#93]
In  flutter app, when the app is paused or detached the app crashes rising this error.

My setup:

void startBackgroundService() async {
  const androidConfig = FlutterBackgroundAndroidConfig(
    notificationTitle: "App is running in background",
    notificationText: "Tap to return to the app",
    notificationImportance: AndroidNotificationImportance.Default,
    enableWifiLock: true,
  );

  bool hasPermissions = await FlutterBackground.hasPermissions;
  if (!hasPermissions) {
    hasPermissions = await FlutterBackground.initialize(androidConfig: androidConfig);
  }

  if (hasPermissions) {
    // Start the background service
    await FlutterBackground.enableBackgroundExecution();
  }
}

E/AndroidRuntime( 4334): FATAL EXCEPTION: main
E/AndroidRuntime( 4334): Process: com.ex.bgservice, PID: 4334
E/AndroidRuntime( 4334): android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3ed1e7a u0 com.ex.bgservice/de.julianassmann.flutter_background.IsolateHolderService}
E/AndroidRuntime( 4334): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
E/AndroidRuntime( 4334): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 4334): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 4334): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 4334): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4334): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 4334): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 4334): Sending signal. PID: 4334 SIG: 9
Lost connection to device.

Please help.
THANKS.

**Comment by JulianAssmann** [comment]
Hi there! Thanks for letting us know you solved the issue. Would you mind:

1. Restoring your original error description
2. Adding your solution as a new comment

This would be really helpful for other users who might encounter the same problem in the future. Documentation of both the problem and its solution is valuable for the community. Thanks for understanding!

**Comment by ramanchhabra22** [comment]
Getting below Crash logs on Crashlytics.

Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d588ae8 u0 com.oooeng/de.julianassmann.flutter_background.IsolateHolderService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

Please help me to resolve this crash @JulianAssmann

**Comment by gettoknowdavid** [comment]
Any solution for this?

**Comment by gettoknowdavid** [comment]
> Solved, THANKS.

Please, how were you able to solve this?

**Comment by parthbhensdadiya7** [comment]
Hi @JulianAssmann ,
I am also experiencing the same crash. Please help me resolve it.

<img width="1302" alt="Image" src="https://github.com/user-attachments/assets/ebd4d725-41df-4481-ab8f-fe592cdd003b" />
